In [1]:
from WumpusWorld import ObsWumpusWorld
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print("Testing")
np.random.seed(2134)
height = 3
width = 3
environment = ObsWumpusWorld(width, height, 0.3, 0)
environment.render()

from ValueIteration import value_iteration
print("Calculating optimal policy")
policy, V, Q = value_iteration(environment, 100, .9)

print("Policy, ", policy)
policy_string="^v<>"
for y in range(height):
    for x in range(width):
        s = environment.get_state(x,y, environment.wumpus_x, environment.wumpus_y)
        print(policy_string[policy[s]], end="")
    print("")

print("Values")
Vxy = np.zeros([height, width])
for wy in range(height):
    for wx in range(width):
        if (environment.maze[wx, wy]!=environment.WALL):
            print("Wumpus at ", wx, wy)
            for y in range(height):
                for x in range(width):
                    s = environment.get_state(x,y, wx, wy)
                    print(policy_string[policy[s]], end="")
                    Vxy[x,y] = V[s]
                print("")
            #plt.matshow(environment.maze.transpose())
            plt.matshow(Vxy.transpose())

Testing
AGain!? 0
AGain!? 1
AGain!? 2
local
[[[0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]]

 [[0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]]]
global
[[[0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 1.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0

AssertionError: 