In [1]:
!python -m pip install nashpy # install nashpy library

In [2]:
import nashpy as nash
import numpy as np
# c.f. https://nashpy.readthedocs.io/en/stable/index.html

## Example

Rock Paper Scizors

In [4]:

# payoff matrix for the first player
rock_paper_scizors_matrix = np.array([
    #R  #P  #S
    [0, -1, 1], # R
    [1, 0, -1], # P
    [-1, 1, 0]  # S
])

# The game is a two-player zero-sum game so we only need to feed the first player payoff matrix
game = nash.Game(rock_paper_scizors_matrix)
print(game)


policy_a = np.array([1, 0, 0]) # probability for each action, R, P, S
policy_b = np.array([0, 1, 0])
# Utility for each player, if they follow the above policies
print("Utility if first player chooses Rock and second player chooses Paper", game[policy_a, policy_b])
print("Best responses ?", game.is_best_response(policy_a, policy_b))

policy_a = np.ones(3, dtype=np.float32) / 3 # random policy
# calculate the best response
nash_eq = game.linear_program()
print("Nash equilibrium:")
print(list(nash_eq)) # nash equilibrium is fully random policies for both sides (1/3 probability for each action)

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]
Utility if first player chooses Rock and second player chooses Paper [-1  1]
Best responses ? (False, True)
Nash equilibrium:::
[array([0.33333333, 0.33333333, 0.33333333]), array([0.33333333, 0.33333333, 0.33333333])]


# 1) A Medieval Duel

#### Define the following 2-player zero-sum game where:
There is 4 actions:

1. Hide
2. Charge with a sword
3. Shoot an arrow 
4. Scoot
    
#### Description:
You engage in a fight with your opponent, which is taking place in the middle of a forest. Both of you own a bow with a couple arrows, and a sword:
- If you hide, your opponent cannot find you, unless he is scooting.
- Charging costs some energy, and shooting spends an arrow.
- Scooting makes you defenseless if your opponent is charging or shooting.

Goals:
- Define the payoff (your choice) for the first player for each action, in function of the action of the opponent.
- Construct the game matrix.
- Compute the nash equilibriums of your game.

In [ ]:

# For each action, define their payoff when the other player picks their own action 
# example

# Remember that the matrix has to be skew-symmetric, and have 0 on the diagonal, so that A + transpose(A) = 0
game_matrix = np.array([
    [hide_to_hide, hide_to_charge, hide_to_arrow, hide_to_scoot],
    [...],
    [...],
    [...]
])
game = nash.Game(game_matrix)

# Test multiple policies, compute the nash equilibrium ... and interpret the policies.

# 2) Prisoner's Dilemma

The prisoner's Dilemma: https://en.wikipedia.org/wiki/Prisoner%27s_dilemma

Goal: Define the prisoner's dilemma game matrix and determine its nash equilibrias.

# 3) Stag Hunt

The Stag Hunt problem: https://en.wikipedia.org/wiki/Stag_hunt

Similarly to the prisoner's dilemma, define the game matrix and determine its nash equilibria